# https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.1
info:
  title: Workleap Renovate Config
  description: Repository containing the shared renovate configurations.
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/renovate-config
  x-cortex-tag: service-renovate-config
  x-cortex-type: library
  x-cortex-slack:
    channels:
      - name: internal-dev-platform
        notificationsEnabled: true
  x-cortex-owners:
    - name: team-internal-developer-platform-backend
      type: GROUP
      provider: CORTEX
  x-cortex-link:
    - name: Documentation
      type: documentation
      url: https://github.com/gsoft-inc/renovate-config
    - type: cortex
      url: https://github.com/gsoft-inc/renovate-config/blob/main/.cortex/catalog/service-renovate-config.yaml
      name: Edit current Cortex entity in GitHub

